// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currency.sql

package pgstore

import (
	"context"
)

const getSaldoPessoaFisicaByID = `-- name: GetSaldoPessoaFisicaByID :one
SELECT saldo FROM pessoa_fisica WHERE id = $1
`

func (q *Queries) GetSaldoPessoaFisicaByID(ctx context.Context, id int32) (float64, error) {
	row := q.db.QueryRow(ctx, getSaldoPessoaFisicaByID, id)
	var saldo float64
	err := row.Scan(&saldo)
	return saldo, err
}

const getSaldoPessoaJuridicaByID = `-- name: GetSaldoPessoaJuridicaByID :one
SELECT saldo FROM pessoa_juridica WHERE id = $1
`

func (q *Queries) GetSaldoPessoaJuridicaByID(ctx context.Context, id int32) (float64, error) {
	row := q.db.QueryRow(ctx, getSaldoPessoaJuridicaByID, id)
	var saldo float64
	err := row.Scan(&saldo)
	return saldo, err
}
