// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgstore

import (
	"context"
)

const createUserPessoaFisica = `-- name: CreateUserPessoaFisica :one
INSERT INTO pessoa_fisica (
  renda_mensal,
  nome_completo,
  email,
  idade,
  celular,
  categoria,
  saldo
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserPessoaFisicaParams struct {
	RendaMensal  float64 `json:"renda_mensal"`
	NomeCompleto string  `json:"nome_completo"`
	Email        string  `json:"email"`
	Idade        int32   `json:"idade"`
	Celular      string  `json:"celular"`
	Categoria    string  `json:"categoria"`
	Saldo        float64 `json:"saldo"`
}

func (q *Queries) CreateUserPessoaFisica(ctx context.Context, arg CreateUserPessoaFisicaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserPessoaFisica,
		arg.RendaMensal,
		arg.NomeCompleto,
		arg.Email,
		arg.Idade,
		arg.Celular,
		arg.Categoria,
		arg.Saldo,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createUserPessoaJuridica = `-- name: CreateUserPessoaJuridica :one
INSERT INTO pessoa_juridica (
  faturamento,
  nome_fantasia,
  email_corporativo,
  idade,
  celular,
  categoria,
  saldo
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserPessoaJuridicaParams struct {
	Faturamento      float64 `json:"faturamento"`
	NomeFantasia     string  `json:"nome_fantasia"`
	EmailCorporativo string  `json:"email_corporativo"`
	Idade            int32   `json:"idade"`
	Celular          string  `json:"celular"`
	Categoria        string  `json:"categoria"`
	Saldo            float64 `json:"saldo"`
}

func (q *Queries) CreateUserPessoaJuridica(ctx context.Context, arg CreateUserPessoaJuridicaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserPessoaJuridica,
		arg.Faturamento,
		arg.NomeFantasia,
		arg.EmailCorporativo,
		arg.Idade,
		arg.Celular,
		arg.Categoria,
		arg.Saldo,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
