// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgstore

import (
	"context"
)

const createUserPessoaFisica = `-- name: CreateUserPessoaFisica :one
INSERT INTO pessoa_fisica (
  renda_mensal,
  nome_completo,
  email,
  idade,
  celular,
  categoria,
  saldo
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserPessoaFisicaParams struct {
	RendaMensal  float64 `json:"renda_mensal"`
	NomeCompleto string  `json:"nome_completo"`
	Email        string  `json:"email"`
	Idade        int32   `json:"idade"`
	Celular      string  `json:"celular"`
	Categoria    string  `json:"categoria"`
	Saldo        float64 `json:"saldo"`
}

func (q *Queries) CreateUserPessoaFisica(ctx context.Context, arg CreateUserPessoaFisicaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserPessoaFisica,
		arg.RendaMensal,
		arg.NomeCompleto,
		arg.Email,
		arg.Idade,
		arg.Celular,
		arg.Categoria,
		arg.Saldo,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createUserPessoaJuridica = `-- name: CreateUserPessoaJuridica :one
INSERT INTO pessoa_juridica (
  faturamento,
  nome_fantasia,
  email_corporativo,
  idade,
  celular,
  categoria,
  saldo
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserPessoaJuridicaParams struct {
	Faturamento      float64 `json:"faturamento"`
	NomeFantasia     string  `json:"nome_fantasia"`
	EmailCorporativo string  `json:"email_corporativo"`
	Idade            int32   `json:"idade"`
	Celular          string  `json:"celular"`
	Categoria        string  `json:"categoria"`
	Saldo            float64 `json:"saldo"`
}

func (q *Queries) CreateUserPessoaJuridica(ctx context.Context, arg CreateUserPessoaJuridicaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserPessoaJuridica,
		arg.Faturamento,
		arg.NomeFantasia,
		arg.EmailCorporativo,
		arg.Idade,
		arg.Celular,
		arg.Categoria,
		arg.Saldo,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUserPessoaFisica = `-- name: DeleteUserPessoaFisica :one
DELETE FROM pessoa_fisica WHERE id = $1
RETURNING id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo
`

func (q *Queries) DeleteUserPessoaFisica(ctx context.Context, id int32) (PessoaFisica, error) {
	row := q.db.QueryRow(ctx, deleteUserPessoaFisica, id)
	var i PessoaFisica
	err := row.Scan(
		&i.ID,
		&i.RendaMensal,
		&i.Idade,
		&i.NomeCompleto,
		&i.Celular,
		&i.Email,
		&i.Categoria,
		&i.Saldo,
	)
	return i, err
}

const deleteUserPessoaJuridica = `-- name: DeleteUserPessoaJuridica :one
DELETE FROM pessoa_juridica WHERE id = $1
RETURNING id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo
`

func (q *Queries) DeleteUserPessoaJuridica(ctx context.Context, id int32) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, deleteUserPessoaJuridica, id)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
	)
	return i, err
}

const getUserPessoaFisicaByEmail = `-- name: GetUserPessoaFisicaByEmail :one
SELECT id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo FROM pessoa_fisica
WHERE email = $1
`

func (q *Queries) GetUserPessoaFisicaByEmail(ctx context.Context, email string) (PessoaFisica, error) {
	row := q.db.QueryRow(ctx, getUserPessoaFisicaByEmail, email)
	var i PessoaFisica
	err := row.Scan(
		&i.ID,
		&i.RendaMensal,
		&i.Idade,
		&i.NomeCompleto,
		&i.Celular,
		&i.Email,
		&i.Categoria,
		&i.Saldo,
	)
	return i, err
}

const getUserPessoaFisicaByID = `-- name: GetUserPessoaFisicaByID :one
SELECT id, renda_mensal, idade, nome_completo, celular, email, categoria, saldo FROM pessoa_fisica
WHERE id = $1
`

func (q *Queries) GetUserPessoaFisicaByID(ctx context.Context, id int32) (PessoaFisica, error) {
	row := q.db.QueryRow(ctx, getUserPessoaFisicaByID, id)
	var i PessoaFisica
	err := row.Scan(
		&i.ID,
		&i.RendaMensal,
		&i.Idade,
		&i.NomeCompleto,
		&i.Celular,
		&i.Email,
		&i.Categoria,
		&i.Saldo,
	)
	return i, err
}

const getUserPessoaJuridicaByEmail = `-- name: GetUserPessoaJuridicaByEmail :one
SELECT id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo FROM pessoa_juridica
WHERE email_corporativo = $1
`

func (q *Queries) GetUserPessoaJuridicaByEmail(ctx context.Context, emailCorporativo string) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, getUserPessoaJuridicaByEmail, emailCorporativo)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
	)
	return i, err
}

const getUserPessoaJuridicaByID = `-- name: GetUserPessoaJuridicaByID :one
SELECT id, faturamento, idade, nome_fantasia, celular, email_corporativo, categoria, saldo FROM pessoa_juridica
WHERE id = $1
`

func (q *Queries) GetUserPessoaJuridicaByID(ctx context.Context, id int32) (PessoaJuridica, error) {
	row := q.db.QueryRow(ctx, getUserPessoaJuridicaByID, id)
	var i PessoaJuridica
	err := row.Scan(
		&i.ID,
		&i.Faturamento,
		&i.Idade,
		&i.NomeFantasia,
		&i.Celular,
		&i.EmailCorporativo,
		&i.Categoria,
		&i.Saldo,
	)
	return i, err
}
